UPDATE pays set capitale = 'Paris' WHERE nom = 'France';
UPDATE pays set capitale = 'Berlin' WHERE nom = 'Germany';
UPDATE pays set capitale = 'Madrid' WHERE nom = 'Spain';
UPDATE pays set capitale = 'London' WHERE nom = 'United Kingdom';
UPDATE pays set capitale = 'Warsaw' WHERE nom = 'Poland';
UPDATE pays set capitale = 'Rome' WHERE nom = 'Italy';
UPDATE pays set capitale = 'Bern' WHERE nom = 'Switzerland';
UPDATE pays set capitale = 'Athens' WHERE nom = 'Greece';
UPDATE pays set capitale = 'Lisbon' WHERE nom = 'Portugal';
UPDATE pays set capitale = 'Minsk' WHERE nom = 'Belarus';
UPDATE pays set capitale = 'Budapest' WHERE nom = 'Hungary';
UPDATE pays set capitale = 'Vienna' WHERE nom = 'Austria';
UPDATE pays set capitale = 'Ankara' WHERE nom = 'Turkey';
UPDATE pays set capitale = 'Moscow' WHERE nom = 'Russia';
UPDATE pays set capitale = 'Beijing' WHERE nom = 'China';
UPDATE pays set capitale = 'Tokyo' WHERE nom = 'Japan';
UPDATE pays set capitale = 'New Delhi' WHERE nom = 'India';
UPDATE pays set capitale = 'Jakarta' WHERE nom = 'Indonesia';
UPDATE pays set capitale = 'Riyadh' WHERE nom = 'Saudi Arabia';
UPDATE pays set capitale = 'Washington' WHERE nom = 'United States';
UPDATE pays set capitale = 'Ottawa' WHERE nom = 'Canada';
UPDATE pays set capitale = 'Mexico City' WHERE nom = 'Mexico';
UPDATE pays set capitale = 'Sao Paulo' WHERE nom = 'Brazil';
UPDATE pays set capitale = 'Brasilia' WHERE nom = 'Brazil';
UPDATE pays set capitale = 'Buenos Aires' WHERE nom = 'Argentina';
UPDATE pays set capitale = 'Santiago' WHERE nom = 'Chile';